---

- name: Template the forms
  template:
    src: "{{ item }}.j2"
    dest: "{{ config_location }}/openmrs-module-initializer/configuration/concepts/{{ item }}"
  with_items:
    - assessment.csv

- name: Template the clinical config
  template:
    src: "{{ item }}.j2"
    dest: "{{ config_location }}/openmrs/apps/clinical/{{ item }}"
  with_items:
    - app.json
    - formConditions.js

